// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getFeeds.sql

package database

import (
	"context"
	"database/sql"
)

const getFeeds = `-- name: GetFeeds :many
SELECT f.name as FeedName, f.url as FeedUrl, u.name as UserName
FROM feeds f
JOIN users u ON f.user_id = u.id
`

type GetFeedsRow struct {
	Feedname sql.NullString
	Feedurl  sql.NullString
	Username sql.NullString
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(&i.Feedname, &i.Feedurl, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
